# Generated by Django 5.2.7 on 2025-10-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_categories_options_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='Категория',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='Колличество на складе',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='Фотография',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='Цена',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='Подкатегория',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory'),
        ),
    ]
