# Generated by Django 5.2.7 on 2025-10-21 14:42

from django.db import migrations

def combine_names(apps, schema_editor):
    # qwe = ('C:/Users/Lenovo/Pictures/Screenshots/Снимок экрана 2024-12-16 172944.png',
    #       "Электрогитара Gibson Les Paul Standard '50s",
    #       4.5,
    #       100.0,
    #       33.0,
    #       'США',
    #       "Gibson Les Paul Standard '50s — это воплощение классического американского "
    #       'звучания. Корпус из махагони с топом из клёна обеспечивает насыщенный '
    #       'сустейн и богатый тембр. Два хамбакера Burstbucker дают мощный, плотный '
    #       "звук, идеально подходящий для рока, блюза и хард-рока. Гриф с профилем '50s "
    #       'Rounded обеспечивает комфортную игру, а винтажная фурнитура добавляет '
    #       'аутентичности. Эта модель — выбор профессионалов, ценящих традиции и '
    #       'качество.',
    #       2499.0,
    #       12,
    #       'гитары',
    #       'Электрогитары')
    #
    # Products = apps.get_model("shop", "Products")

    # Products.objects.create(
    #     image=qwe[0],
    #     name=qwe[1],
    #     weight=qwe[2],
    #     length=qwe[3],
    #     width=qwe[4],
    #     country=qwe[5],
    #     description=qwe[6],
    #     price=qwe[7],
    #     quantity=qwe[8],
    #     category=qwe[9],
    #     sub_category=qwe[10],
    # )

    sub_categories = ['электрогитары', 'Бас гитары', 'акустические гитары', 'классические гитары',
                          'цифровые фортепиано', 'синтезаторы', 'миди контроллеры', 'ударные установки', 'цифровые ударные установки',
                          'перкуссии', 'комплектующие к ударным', 'звуковые карты', 'Студийные мониторы', 'микрофоны',
                          'Студийные наушники', 'DJ-контроллеры', 'кабеля гитарные', 'кабеля микрофонные',
                          'кабеля для акустических систем', 'midi-кабеля']

    SubCategories = apps.get_model("shop", "SubCategory")

    for y in sub_categories:
        SubCategories.objects.create(sub_category_name=str(y).title())


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20251021_1545'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
