# Generated by Django 5.2.7 on 2025-10-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20251021_1742'),
    ]

    operations = [
    ]
