# Generated by Django 5.2.7 on 2025-10-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20251021_1814'),
    ]

    operations = [
    ]
