# Generated by Django 5.2.7 on 2025-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20251022_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Категория',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Страна производства',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Вес товара',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Название товара',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Цена',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Колличество на складе',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Подкатегория',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Длина товара',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Ширина товара',
            new_name='width',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Фотография',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=0, upload_to='media/products_images'),
        ),
    ]
