# Generated by Django 5.2.7 on 2025-10-27 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('courier', 'Курьером'), ('bel-post', 'Бел-почта'), ('Euro-post', 'Евро-почта')], max_length=50)),
                ('shipping_method', models.CharField(choices=[('Erip', 'Ерип'), ('Cash-to-the-courier', 'Наличными курьеру'), ('bank-card', 'Банковская карта')], max_length=50)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('canceled', 'Отменен'), ('created', 'Создан'), ('completed', 'Завершен')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
