# Generated by Django 5.2.7 on 2025-10-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
