# Generated by Django 5.2.7 on 2025-10-27 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delete_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('shipping_to_user', models.BooleanField(default=False, verbose_name='Доставка владельцу аккаунта')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='Область')),
                ('district', models.CharField(blank=True, max_length=150, null=True, verbose_name='Район')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('entrance_number', models.IntegerField(blank=True, null=True, verbose_name='Номер подъезда')),
                ('flat_number', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('post_index', models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс')),
                ('telephone', models.CharField(default='+375 00 000-00-00', max_length=14, verbose_name='Номер телефона')),
                ('payment_method', models.CharField(choices=[('courier', 'Курьером'), ('bel-post', 'Бел-почта'), ('Euro-post', 'Евро-почта')], max_length=50)),
                ('shipping_method', models.CharField(choices=[('Erip', 'Ерип'), ('Cash-to-the-courier', 'Наличными курьеру'), ('bank-card', 'Банковская карта')], max_length=50)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('canceled', 'Отменен'), ('created', 'Создан'), ('completed', 'Завершен')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
