# Generated by Django 5.2.7 on 2025-10-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount_money',
            field=models.FloatField(default=0, verbose_name='Сумма итого'),
        ),
        migrations.AddField(
            model_name='orders',
            name='name_client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
