# Generated by Django 5.2.7 on 2025-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orders_amount_money_orders_name_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='telephone',
            field=models.CharField(default='+375 00 000-00-00', max_length=17, verbose_name='Номер телефона'),
        ),
    ]
