# Generated by Django 5.2.7 on 2025-10-28 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_orders_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(auto_created=True, choices=[('canceled', 'Отменен'), ('created', 'Создан'), ('completed', 'Завершен')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
