# Generated by Django 5.2.7 on 2025-10-28 20:30

import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_orders_comment_alter_orders_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='telephone',
            field=models.CharField(blank=True, default='+375 00 000-00-00', max_length=17, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(auto_created=True, blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
