# Generated by Django 5.2.7 on 2025-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_orders_telephone_alter_orders_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(auto_created=True, choices=[('canceled', 'Отменен'), ('created', 'Создан'), ('in_work', 'В работе'), ('completed', 'Завершен')], default='created', max_length=10),
        ),
    ]
