# Generated by Django 5.2.7 on 2025-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.CharField(default=0, max_length=12, unique=True),
        ),
    ]
