# Generated by Django 5.2.7 on 2025-10-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_orders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
