# Generated by Django 5.2.7 on 2025-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_город_users_номер_дома_users_номер_квартиры_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Город',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Номер дома',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Номер квартиры',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Номер подъезда',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Область',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Почтовый индекс',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Район',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Улица',
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='users',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='users',
            name='entrance_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер подъезда'),
        ),
        migrations.AddField(
            model_name='users',
            name='flat_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='users',
            name='house_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='users',
            name='post_index',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='users',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
