# Generated by Django 5.2.7 on 2025-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_users_город_remove_users_номер_дома_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telephone',
            field=models.CharField(default='+375 00 000-00-00', max_length=14, verbose_name='Номер телефона'),
        ),
    ]
